In [1]:
import numpy as np

## Задание 1

In [2]:
N = 10

arr = np.arange(0, N)[::-1]
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

In [3]:
N = 5

diag_ = np.diag(np.random.permutation(N))
sum_ = np.trace(diag_)

print(f'Диагональная матрица:\n{diag_}\nСумму диагональных элементов матрицы: {sum_}')

Диагональная матрица:
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 0]
 [0 0 0 0 4]]
Сумму диагональных элементов матрицы: 10


## Задание 3

In [4]:
left = np.array([[4., 2., 1.], [1., 3., 0.], [0., 5., 4.]])
right = np.array([4., 12., -3.])
solve_ = np.linalg.solve(left, right)

print(f'x = {solve_[0]}, y = {solve_[1]}, z = {solve_[2]}')

x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555


## Задание 4

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [8]:
next_user_length = np.linalg.norm(next_user_stats)

cosines = []
for user_stats in users_stats:
    user_length = np.linalg.norm(user_stats)
    cosine = np.dot(user_stats, next_user_stats) / (user_length * next_user_length)
    cosines.append(cosine)
    
print(f'Самый похожий пользователь (ID): {cosines.index(max(cosines))+1}. Косинусное сходство между векторами {max(cosines)}')

Самый похожий пользователь (ID): 8. Косинусное сходство между векторами 0.9486832980505138
